{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.noeppi_noeppi.tools",
    "module": "plugin",
    "version": "2.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ModGradle-2.0.14.jar",
          "url": "ModGradle-2.0.14.jar",
          "size": 209856,
          "sha512": "cca7a9dc9c253ccfa383ed334324f6c2756bd81bce9c38f02d490c890fa198fc3a1ac9e51218d9e0808497dc0a0a1e969a9e4b33c358c2c3a292907860f806f1",
          "sha256": "8791afb6502f22af736b8a60975c0cc6cc467c149158e321ddcf5ae48bf054f6",
          "sha1": "e6f8d33d516c1f40e8db9b10977b485f90bce6d5",
          "md5": "ad2640173fc6a5289aa96d5a17377cba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "strictly": "[3.0.2,)",
            "requires": "[3.0.2,)",
            "prefers": "3.0.2"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "strictly": "[0.4.9,)",
            "requires": "[0.4.9,)",
            "prefers": "0.4.9"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "ForgeGradle",
          "version": {
            "strictly": "[5.1.31,5.2)",
            "requires": "[5.1.31,5.2)",
            "prefers": "5.1.31"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "strictly": "[3.0.8,)",
            "requires": "[3.0.8,)",
            "prefers": "3.0.8"
          }
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "strictly": "[2.1.0,)",
            "requires": "[2.1.0,)",
            "prefers": "2.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "strictly": "[2.9.0,)",
            "requires": "[2.9.0,)",
            "prefers": "2.9.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "strictly": "[31.0.1-jre,)",
            "requires": "[31.0.1-jre,)",
            "prefers": "31.0.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "strictly": "[3.12.0,4.0.0)",
            "requires": "[3.12.0,4.0.0)",
            "prefers": "3.12.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "strictly": "[2.11.0,)",
            "requires": "[2.11.0,)",
            "prefers": "2.11.0"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "strictly": "[3.8.4,)",
            "requires": "[3.8.4,)",
            "prefers": "3.8.4"
          }
        },
        {
          "group": "io.github.noeppi_noeppi.tools",
          "module": "CurseWrapper",
          "version": {
            "strictly": "[1.0,)",
            "requires": "[1.0,)",
            "prefers": "1.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "strictly": "[2.17.2,)",
            "requires": "[2.17.2,)"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "strictly": "[2.17.2,)",
            "requires": "[2.17.2,)"
          }
        }
      ],
      "files": [
        {
          "name": "ModGradle-2.0.14.jar",
          "url": "ModGradle-2.0.14.jar",
          "size": 209856,
          "sha512": "cca7a9dc9c253ccfa383ed334324f6c2756bd81bce9c38f02d490c890fa198fc3a1ac9e51218d9e0808497dc0a0a1e969a9e4b33c358c2c3a292907860f806f1",
          "sha256": "8791afb6502f22af736b8a60975c0cc6cc467c149158e321ddcf5ae48bf054f6",
          "sha1": "e6f8d33d516c1f40e8db9b10977b485f90bce6d5",
          "md5": "ad2640173fc6a5289aa96d5a17377cba"
        }
      ]
    }
  ]
}
