{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.noeppi_noeppi.tools",
    "module": "plugin",
    "version": "1.0.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ModGradle-1.0.36.jar",
          "url": "ModGradle-1.0.36.jar",
          "size": 284154,
          "sha512": "e176806f939924a5c9ff8bcfe3fe15f1e46c384aee74fb2a792ee967f583be3b16084ca56b5578f2a310f87b4cd1bee6e85613e3fffde0d2c412d6b83aa6fbcf",
          "sha256": "02e2a0896ee9567ce4cff7300c50b0db54c83ff0d71d89099c318a9dac49ac50",
          "sha1": "49a37cd1267bbb6396171d568934ccaa9025b36a",
          "md5": "b5f9fcd850f083017303a587c90fe651"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "strictly": "[3.0.1,)",
            "requires": "[3.0.1,)",
            "prefers": "3.0.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "strictly": "[0.4.3,)",
            "requires": "[0.4.3,)",
            "prefers": "0.4.3"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "ForgeGradle",
          "version": {
            "strictly": "[5.1.21,5.2)",
            "requires": "[5.1.21,5.2)",
            "prefers": "5.1.23"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "strictly": "[3.0.8,)",
            "requires": "[3.0.8,)",
            "prefers": "3.0.8"
          }
        },
        {
          "group": "org.parchmentmc",
          "module": "librarian",
          "version": {
            "strictly": "[1.1.4,)",
            "requires": "[1.1.4,)",
            "prefers": "1.1.4"
          }
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "strictly": "[2.0.0,)",
            "requires": "[2.0.0,)",
            "prefers": "2.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "strictly": "[2.8.7,)",
            "requires": "[2.8.7,)",
            "prefers": "2.8.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "strictly": "[30.1.1-jre,)",
            "requires": "[30.1.1-jre,)",
            "prefers": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "strictly": "[3.12.0,4.0.0)",
            "requires": "[3.12.0,4.0.0)",
            "prefers": "3.12.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "strictly": "[2.11.0,)",
            "requires": "[2.11.0,)",
            "prefers": "2.11.0"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "strictly": "[3.8.1,)",
            "requires": "[3.8.1,)",
            "prefers": "3.8.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "strictly": "[2.10.0,)",
            "requires": "[2.10.0,)",
            "prefers": "2.10.0"
          }
        },
        {
          "group": "org.scala-lang",
          "module": "scala-library",
          "version": {
            "strictly": "[2.13.1,2.14.0)",
            "requires": "[2.13.1,2.14.0)",
            "prefers": "2.13.1"
          }
        },
        {
          "group": "org.scala-lang.modules",
          "module": "scala-parser-combinators_2.13",
          "version": {
            "strictly": "[2.0.0,)",
            "requires": "[2.0.0,)",
            "prefers": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ModGradle-1.0.36.jar",
          "url": "ModGradle-1.0.36.jar",
          "size": 284154,
          "sha512": "e176806f939924a5c9ff8bcfe3fe15f1e46c384aee74fb2a792ee967f583be3b16084ca56b5578f2a310f87b4cd1bee6e85613e3fffde0d2c412d6b83aa6fbcf",
          "sha256": "02e2a0896ee9567ce4cff7300c50b0db54c83ff0d71d89099c318a9dac49ac50",
          "sha1": "49a37cd1267bbb6396171d568934ccaa9025b36a",
          "md5": "b5f9fcd850f083017303a587c90fe651"
        }
      ]
    }
  ]
}
