{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.noeppi_noeppi.tools",
    "module": "plugin",
    "version": "2.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ModGradle-2.0.10.jar",
          "url": "ModGradle-2.0.10.jar",
          "size": 208125,
          "sha512": "e2ba6a406e796b9b4237411f60ba4a39af6b00e82a8ac502c0728ad6e2e86e51ca6b6071b5a61c7faa40b97b8e56338e51fc561b0deb039ff8c6a3f5e8388032",
          "sha256": "04b8739a4484289350ebade8994d1787ec51a4a746ba4aadc9460550dd0a16fb",
          "sha1": "a8d06b93b4c213bd4dde1915a14758e8a0233c42",
          "md5": "2f81e179357078eb9107bc52a3780939"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "strictly": "[3.0.1,)",
            "requires": "[3.0.1,)",
            "prefers": "3.0.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "strictly": "[0.4.3,)",
            "requires": "[0.4.3,)",
            "prefers": "0.4.3"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "ForgeGradle",
          "version": {
            "strictly": "[5.1.26,5.2)",
            "requires": "[5.1.26,5.2)",
            "prefers": "5.1.27"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "strictly": "[3.0.8,)",
            "requires": "[3.0.8,)",
            "prefers": "3.0.8"
          }
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "strictly": "[2.0.0,)",
            "requires": "[2.0.0,)",
            "prefers": "2.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "strictly": "[2.8.7,)",
            "requires": "[2.8.7,)",
            "prefers": "2.8.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "strictly": "[30.1.1-jre,)",
            "requires": "[30.1.1-jre,)",
            "prefers": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "strictly": "[3.12.0,4.0.0)",
            "requires": "[3.12.0,4.0.0)",
            "prefers": "3.12.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "strictly": "[2.11.0,)",
            "requires": "[2.11.0,)",
            "prefers": "2.11.0"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "strictly": "[3.8.1,)",
            "requires": "[3.8.1,)",
            "prefers": "3.8.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "strictly": "[2.10.0,)",
            "requires": "[2.10.0,)",
            "prefers": "2.10.0"
          }
        },
        {
          "group": "io.github.noeppi_noeppi.tools",
          "module": "CurseWrapper",
          "version": {
            "strictly": "[1.0,)",
            "requires": "[1.0,)",
            "prefers": "1.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "strictly": "[2.17.1,)",
            "requires": "[2.17.1,)"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "strictly": "[2.17.1,)",
            "requires": "[2.17.1,)"
          }
        }
      ],
      "files": [
        {
          "name": "ModGradle-2.0.10.jar",
          "url": "ModGradle-2.0.10.jar",
          "size": 208125,
          "sha512": "e2ba6a406e796b9b4237411f60ba4a39af6b00e82a8ac502c0728ad6e2e86e51ca6b6071b5a61c7faa40b97b8e56338e51fc561b0deb039ff8c6a3f5e8388032",
          "sha256": "04b8739a4484289350ebade8994d1787ec51a4a746ba4aadc9460550dd0a16fb",
          "sha1": "a8d06b93b4c213bd4dde1915a14758e8a0233c42",
          "md5": "2f81e179357078eb9107bc52a3780939"
        }
      ]
    }
  ]
}
