{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.noeppi_noeppi.tools",
    "module": "CurseWrapperServer",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "CurseWrapperServer-0.3.jar",
          "url": "CurseWrapperServer-0.3.jar",
          "size": 101728,
          "sha512": "f86a3bd577f586a353ca4d55ec769ae5a907cacf45f5a36bd73ef10e7c0ea873b9aff796e82444b8b5d56fba7ded194ab5399c3db11f82401a3c0f5e3cf51c6f",
          "sha256": "a6aa88cad8bdc81ffc94c25db2c4c618c08e986d755c88750ff2bede977bb058",
          "sha1": "9c7a353fe13d41a8a8a8045717c5e47791d95a5d",
          "md5": "55e77ea582ac3ddd998d9ad0eb308f97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "com.sparkjava",
          "module": "spark-core",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-jre"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.33"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-jdk14",
          "version": {
            "requires": "1.7.33"
          }
        }
      ],
      "files": [
        {
          "name": "CurseWrapperServer-0.3.jar",
          "url": "CurseWrapperServer-0.3.jar",
          "size": 101728,
          "sha512": "f86a3bd577f586a353ca4d55ec769ae5a907cacf45f5a36bd73ef10e7c0ea873b9aff796e82444b8b5d56fba7ded194ab5399c3db11f82401a3c0f5e3cf51c6f",
          "sha256": "a6aa88cad8bdc81ffc94c25db2c4c618c08e986d755c88750ff2bede977bb058",
          "sha1": "9c7a353fe13d41a8a8a8045717c5e47791d95a5d",
          "md5": "55e77ea582ac3ddd998d9ad0eb308f97"
        }
      ]
    }
  ]
}
