{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.noeppi_noeppi.tools",
    "module": "plugin",
    "version": "2.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ModGradle-2.0.13.jar",
          "url": "ModGradle-2.0.13.jar",
          "size": 209839,
          "sha512": "755391a5a811b11540dddbedfc8268f60fcfd245a973a773103030aeb4678c3153d6d9a3d7dce136c66acab9f8f612626c481cc0df0824e89b6b49e00c2bf6ca",
          "sha256": "5ba69f65b671acbae2e4b179b4315d361a37dbce8952e21c4b724e00f8cd2657",
          "sha1": "dc34ae148038320e2ee13f922a9144aea2c340d9",
          "md5": "f25d00f9a5ac1e37b6bdddc4ff0180db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "strictly": "[3.0.2,)",
            "requires": "[3.0.2,)",
            "prefers": "3.0.2"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "strictly": "[0.4.9,)",
            "requires": "[0.4.9,)",
            "prefers": "0.4.9"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "ForgeGradle",
          "version": {
            "strictly": "[5.1.31,5.2)",
            "requires": "[5.1.31,5.2)",
            "prefers": "5.1.31"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "strictly": "[3.0.8,)",
            "requires": "[3.0.8,)",
            "prefers": "3.0.8"
          }
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "strictly": "[2.1.0,)",
            "requires": "[2.1.0,)",
            "prefers": "2.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "strictly": "[2.9.0,)",
            "requires": "[2.9.0,)",
            "prefers": "2.9.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "strictly": "[31.0.1-jre,)",
            "requires": "[31.0.1-jre,)",
            "prefers": "31.0.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "strictly": "[3.12.0,4.0.0)",
            "requires": "[3.12.0,4.0.0)",
            "prefers": "3.12.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "strictly": "[2.11.0,)",
            "requires": "[2.11.0,)",
            "prefers": "2.11.0"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "strictly": "[3.8.4,)",
            "requires": "[3.8.4,)",
            "prefers": "3.8.4"
          }
        },
        {
          "group": "io.github.noeppi_noeppi.tools",
          "module": "CurseWrapper",
          "version": {
            "strictly": "[1.0,)",
            "requires": "[1.0,)",
            "prefers": "1.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "strictly": "[2.17.2,)",
            "requires": "[2.17.2,)"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "strictly": "[2.17.2,)",
            "requires": "[2.17.2,)"
          }
        }
      ],
      "files": [
        {
          "name": "ModGradle-2.0.13.jar",
          "url": "ModGradle-2.0.13.jar",
          "size": 209839,
          "sha512": "755391a5a811b11540dddbedfc8268f60fcfd245a973a773103030aeb4678c3153d6d9a3d7dce136c66acab9f8f612626c481cc0df0824e89b6b49e00c2bf6ca",
          "sha256": "5ba69f65b671acbae2e4b179b4315d361a37dbce8952e21c4b724e00f8cd2657",
          "sha1": "dc34ae148038320e2ee13f922a9144aea2c340d9",
          "md5": "f25d00f9a5ac1e37b6bdddc4ff0180db"
        }
      ]
    }
  ]
}
