{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.noeppi_noeppi.tools",
    "module": "plugin",
    "version": "1.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ModGradle-1.0.22.jar",
          "url": "ModGradle-1.0.22.jar",
          "size": 246796,
          "sha512": "59ce03f0a9990fecedcedc53034128a062c48d5498a75c9df906d497d651117f864ff08e36fcbac5108748de4310885dade81d56274100abd6248c9e549c7a42",
          "sha256": "d7f42a360a39758dac9d014c0b37c29f89433359ed4fae01a0b20256d1920aba",
          "sha1": "e11fa112c174303445e82b4699321603800c02e3",
          "md5": "16c28ccb90d55272e66af7c9eda8955a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "strictly": "[3.0.1,)",
            "requires": "[3.0.1,)",
            "prefers": "3.0.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "strictly": "[0.4.3,)",
            "requires": "[0.4.3,)",
            "prefers": "0.4.3"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "ForgeGradle",
          "version": {
            "strictly": "[5.1.20,5.2)",
            "requires": "[5.1.20,5.2)",
            "prefers": "5.1.20"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "strictly": "[3.0.8,)",
            "requires": "[3.0.8,)",
            "prefers": "3.0.8"
          }
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "strictly": "[2.0.0,)",
            "requires": "[2.0.0,)",
            "prefers": "2.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "strictly": "[2.8.7,)",
            "requires": "[2.8.7,)",
            "prefers": "2.8.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "strictly": "[30.1.1-jre,)",
            "requires": "[30.1.1-jre,)",
            "prefers": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "strictly": "[3.12.0,4.0.0)",
            "requires": "[3.12.0,4.0.0)",
            "prefers": "3.12.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "strictly": "[2.11.0,)",
            "requires": "[2.11.0,)",
            "prefers": "2.11.0"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "strictly": "[3.8.1,)",
            "requires": "[3.8.1,)",
            "prefers": "3.8.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "strictly": "[2.10.0,)",
            "requires": "[2.10.0,)",
            "prefers": "2.10.0"
          }
        },
        {
          "group": "org.scala-lang",
          "module": "scala-library",
          "version": {
            "strictly": "[2.13.1,2.14.0)",
            "requires": "[2.13.1,2.14.0)",
            "prefers": "2.13.1"
          }
        },
        {
          "group": "org.scala-lang.modules",
          "module": "scala-parser-combinators_2.13",
          "version": {
            "strictly": "[2.0.0,)",
            "requires": "[2.0.0,)",
            "prefers": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ModGradle-1.0.22.jar",
          "url": "ModGradle-1.0.22.jar",
          "size": 246796,
          "sha512": "59ce03f0a9990fecedcedc53034128a062c48d5498a75c9df906d497d651117f864ff08e36fcbac5108748de4310885dade81d56274100abd6248c9e549c7a42",
          "sha256": "d7f42a360a39758dac9d014c0b37c29f89433359ed4fae01a0b20256d1920aba",
          "sha1": "e11fa112c174303445e82b4699321603800c02e3",
          "md5": "16c28ccb90d55272e66af7c9eda8955a"
        }
      ]
    }
  ]
}
