{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.noeppi_noeppi.tools",
    "module": "plugin",
    "version": "1.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ModGradle-1.0.19.jar",
          "url": "ModGradle-1.0.19.jar",
          "size": 212257,
          "sha512": "a4a5fc59655ec888c4d6e9d4a719abd79d36d70088efa6e2a6fb592c306f1c5b2e2657e6f6d21bfc33a3a7d1442490d5a26480c8eed4079e44ac08ea50d731a2",
          "sha256": "a0a5ac34c604b175e651810487b053ab1a48f8bd1c8035687e646986d18364f3",
          "sha1": "44accec7d4be862b23feab90d4d1bc56694f48cc",
          "md5": "178b6e4769af9e3e748316240620f00a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "strictly": "[3.0.1,)",
            "requires": "[3.0.1,)",
            "prefers": "3.0.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "strictly": "[0.4.3,)",
            "requires": "[0.4.3,)",
            "prefers": "0.4.3"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "ForgeGradle",
          "version": {
            "strictly": "[5.1.14,5.2)",
            "requires": "[5.1.14,5.2)",
            "prefers": "5.1.14"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "strictly": "[3.0.8,)",
            "requires": "[3.0.8,)",
            "prefers": "3.0.8"
          }
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "strictly": "[2.0.0,)",
            "requires": "[2.0.0,)",
            "prefers": "2.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "strictly": "[2.8.7,)",
            "requires": "[2.8.7,)",
            "prefers": "2.8.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "strictly": "[30.1.1-jre,)",
            "requires": "[30.1.1-jre,)",
            "prefers": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "strictly": "[3.12.0,4.0.0)",
            "requires": "[3.12.0,4.0.0)",
            "prefers": "3.12.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "strictly": "[2.11.0,)",
            "requires": "[2.11.0,)",
            "prefers": "2.11.0"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "strictly": "[3.8.1,)",
            "requires": "[3.8.1,)",
            "prefers": "3.8.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "strictly": "[2.10.0,)",
            "requires": "[2.10.0,)",
            "prefers": "2.10.0"
          }
        },
        {
          "group": "org.scala-lang",
          "module": "scala-library",
          "version": {
            "strictly": "[2.13.1,2.14.0)",
            "requires": "[2.13.1,2.14.0)",
            "prefers": "2.13.1"
          }
        },
        {
          "group": "org.scala-lang.modules",
          "module": "scala-parser-combinators_2.13",
          "version": {
            "strictly": "[2.0.0,)",
            "requires": "[2.0.0,)",
            "prefers": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ModGradle-1.0.19.jar",
          "url": "ModGradle-1.0.19.jar",
          "size": 212257,
          "sha512": "a4a5fc59655ec888c4d6e9d4a719abd79d36d70088efa6e2a6fb592c306f1c5b2e2657e6f6d21bfc33a3a7d1442490d5a26480c8eed4079e44ac08ea50d731a2",
          "sha256": "a0a5ac34c604b175e651810487b053ab1a48f8bd1c8035687e646986d18364f3",
          "sha1": "44accec7d4be862b23feab90d4d1bc56694f48cc",
          "md5": "178b6e4769af9e3e748316240620f00a"
        }
      ]
    }
  ]
}
