{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.noeppi_noeppi.tools",
    "module": "CurseWrapperServer",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.noeppi_noeppi.tools",
          "module": "CurseWrapperShared",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "CurseWrapperServer-0.1.jar",
          "url": "CurseWrapperServer-0.1.jar",
          "size": 101174,
          "sha512": "5be132971a8d7b85563cbdd4bad484a8eb385e3672ef16e246f8dcf1a19da8e565bcd1ed317d2f2060effe0a7ad9cf25e7db932096989ee9267194fc4ecb4e42",
          "sha256": "8e14607a0c99649261aec3fb519ffd981312ca3e3b5f198b41330e79f751900f",
          "sha1": "ece3a0294da913403c7ae551ea85b6be0d73c666",
          "md5": "b81477e339e89e564da787ebd063d1cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "com.sparkjava",
          "module": "spark-core",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-jre"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.33"
          }
        },
        {
          "group": "io.github.noeppi_noeppi.tools",
          "module": "CurseWrapperShared",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-jdk14",
          "version": {
            "requires": "1.7.33"
          }
        }
      ],
      "files": [
        {
          "name": "CurseWrapperServer-0.1.jar",
          "url": "CurseWrapperServer-0.1.jar",
          "size": 101174,
          "sha512": "5be132971a8d7b85563cbdd4bad484a8eb385e3672ef16e246f8dcf1a19da8e565bcd1ed317d2f2060effe0a7ad9cf25e7db932096989ee9267194fc4ecb4e42",
          "sha256": "8e14607a0c99649261aec3fb519ffd981312ca3e3b5f198b41330e79f751900f",
          "sha1": "ece3a0294da913403c7ae551ea85b6be0d73c666",
          "md5": "b81477e339e89e564da787ebd063d1cd"
        }
      ]
    }
  ]
}
