{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.noeppi_noeppi.tools",
    "module": "CurseWrapperServer",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.noeppi_noeppi.tools",
          "module": "CurseWrapperShared",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "CurseWrapperServer-0.1.jar",
          "url": "CurseWrapperServer-0.1.jar",
          "size": 101174,
          "sha512": "99ac0289ab73179c040a20385104694867c02728056b863b05819c21797998c9a229b403a47ab81513296f996b2433bff75fa543223d9e0e1696e90b5793581a",
          "sha256": "bc4095fc07365744f4a05841739805c107424e9765fa5c57dbf0e4287a150bbc",
          "sha1": "c04aa903654fbcfa9076215fe2e2fc601b33f200",
          "md5": "3aa82f7c42953365fc95a309d95ba803"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "com.sparkjava",
          "module": "spark-core",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-jre"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.33"
          }
        },
        {
          "group": "io.github.noeppi_noeppi.tools",
          "module": "CurseWrapperShared",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-jdk14",
          "version": {
            "requires": "1.7.33"
          }
        }
      ],
      "files": [
        {
          "name": "CurseWrapperServer-0.1.jar",
          "url": "CurseWrapperServer-0.1.jar",
          "size": 101174,
          "sha512": "99ac0289ab73179c040a20385104694867c02728056b863b05819c21797998c9a229b403a47ab81513296f996b2433bff75fa543223d9e0e1696e90b5793581a",
          "sha256": "bc4095fc07365744f4a05841739805c107424e9765fa5c57dbf0e4287a150bbc",
          "sha1": "c04aa903654fbcfa9076215fe2e2fc601b33f200",
          "md5": "3aa82f7c42953365fc95a309d95ba803"
        }
      ]
    }
  ]
}
