{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.noeppi_noeppi.tools",
    "module": "plugin",
    "version": "1.0.39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ModGradle-1.0.39.jar",
          "url": "ModGradle-1.0.39.jar",
          "size": 297987,
          "sha512": "08e0f5c0e59a809a4d171b4c6cfb5a795ae13156494eef5a32a82e140182e46cf4aa3ea3d1fb2319c1e54052fc8603ebd6c96717ae0627610b551eae79b293e0",
          "sha256": "9ef827329bdf21a8883540cb28ed69b12472d647c32adf5575e836cb25fd207f",
          "sha1": "7d4474e6888330d048c0e0e57598ef13792ead02",
          "md5": "41443823e37b9c15391a557005c1b4bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "strictly": "[3.0.1,)",
            "requires": "[3.0.1,)",
            "prefers": "3.0.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "strictly": "[0.4.3,)",
            "requires": "[0.4.3,)",
            "prefers": "0.4.3"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "ForgeGradle",
          "version": {
            "strictly": "[5.1.21,5.2)",
            "requires": "[5.1.21,5.2)",
            "prefers": "5.1.23"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "strictly": "[3.0.8,)",
            "requires": "[3.0.8,)",
            "prefers": "3.0.8"
          }
        },
        {
          "group": "org.parchmentmc",
          "module": "librarian",
          "version": {
            "strictly": "[1.1.4,)",
            "requires": "[1.1.4,)",
            "prefers": "1.1.4"
          }
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "strictly": "[2.0.0,)",
            "requires": "[2.0.0,)",
            "prefers": "2.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "strictly": "[2.8.7,)",
            "requires": "[2.8.7,)",
            "prefers": "2.8.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "strictly": "[30.1.1-jre,)",
            "requires": "[30.1.1-jre,)",
            "prefers": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "strictly": "[3.12.0,4.0.0)",
            "requires": "[3.12.0,4.0.0)",
            "prefers": "3.12.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "strictly": "[2.11.0,)",
            "requires": "[2.11.0,)",
            "prefers": "2.11.0"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "strictly": "[3.8.1,)",
            "requires": "[3.8.1,)",
            "prefers": "3.8.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "strictly": "[2.10.0,)",
            "requires": "[2.10.0,)",
            "prefers": "2.10.0"
          }
        },
        {
          "group": "org.scala-lang",
          "module": "scala-library",
          "version": {
            "strictly": "[2.13.1,2.14.0)",
            "requires": "[2.13.1,2.14.0)",
            "prefers": "2.13.1"
          }
        },
        {
          "group": "org.scala-lang.modules",
          "module": "scala-parser-combinators_2.13",
          "version": {
            "strictly": "[2.0.0,)",
            "requires": "[2.0.0,)",
            "prefers": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ModGradle-1.0.39.jar",
          "url": "ModGradle-1.0.39.jar",
          "size": 297987,
          "sha512": "08e0f5c0e59a809a4d171b4c6cfb5a795ae13156494eef5a32a82e140182e46cf4aa3ea3d1fb2319c1e54052fc8603ebd6c96717ae0627610b551eae79b293e0",
          "sha256": "9ef827329bdf21a8883540cb28ed69b12472d647c32adf5575e836cb25fd207f",
          "sha1": "7d4474e6888330d048c0e0e57598ef13792ead02",
          "md5": "41443823e37b9c15391a557005c1b4bc"
        }
      ]
    }
  ]
}
