{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.noeppi_noeppi.tools",
    "module": "CurseWrapper",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.noeppi_noeppi.tools",
          "module": "CurseWrapperShared",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "CurseWrapper-0.1.jar",
          "url": "CurseWrapper-0.1.jar",
          "size": 17282,
          "sha512": "004f1364e1a216f77eccafc9c748bdd3087d6321125f56c635787039ec2ce9f27701ddae8150211fa38371bf33fed6984d023b60695e104ca5f0d4c0d32b8ce8",
          "sha256": "c16fa458696a3cea2ef6dc23bef19ebbd18d5974c9f6c8384d029e3fe5876c0d",
          "sha1": "13d3a5b044883cbc5eb4a4b5a1a06feed1a2b8e5",
          "md5": "126b87558061c96234078d13c7f16587"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.noeppi_noeppi.tools",
          "module": "CurseWrapperShared",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "CurseWrapper-0.1.jar",
          "url": "CurseWrapper-0.1.jar",
          "size": 17282,
          "sha512": "004f1364e1a216f77eccafc9c748bdd3087d6321125f56c635787039ec2ce9f27701ddae8150211fa38371bf33fed6984d023b60695e104ca5f0d4c0d32b8ce8",
          "sha256": "c16fa458696a3cea2ef6dc23bef19ebbd18d5974c9f6c8384d029e3fe5876c0d",
          "sha1": "13d3a5b044883cbc5eb4a4b5a1a06feed1a2b8e5",
          "md5": "126b87558061c96234078d13c7f16587"
        }
      ]
    }
  ]
}
