{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.noeppi_noeppi.tools",
    "module": "CurseWrapper",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.noeppi_noeppi.tools",
          "module": "CurseWrapperShared",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "CurseWrapper-0.1.jar",
          "url": "CurseWrapper-0.1.jar",
          "size": 17282,
          "sha512": "645d24cd36d11bf3fa6bd5c4b40a5c302aaf0540149909b37e916a6296cb8a57f7c09679076bbd97a8f469f77a6dec8e0bc1e9fd2fa2dc875abaffbd7448466f",
          "sha256": "566b7041046fc4067caa340c004934ae275d791fbe0918a24af01a9705c6883f",
          "sha1": "61749cc5b7dc260050e088dee818d47790a60335",
          "md5": "854225dcba98b83ff0d378b7183fa696"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.noeppi_noeppi.tools",
          "module": "CurseWrapperShared",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "CurseWrapper-0.1.jar",
          "url": "CurseWrapper-0.1.jar",
          "size": 17282,
          "sha512": "645d24cd36d11bf3fa6bd5c4b40a5c302aaf0540149909b37e916a6296cb8a57f7c09679076bbd97a8f469f77a6dec8e0bc1e9fd2fa2dc875abaffbd7448466f",
          "sha256": "566b7041046fc4067caa340c004934ae275d791fbe0918a24af01a9705c6883f",
          "sha1": "61749cc5b7dc260050e088dee818d47790a60335",
          "md5": "854225dcba98b83ff0d378b7183fa696"
        }
      ]
    }
  ]
}
