{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.noeppi_noeppi.tools",
    "module": "CurseWrapper",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.noeppi_noeppi.tools",
          "module": "CurseWrapperShared",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "CurseWrapper-0.1.jar",
          "url": "CurseWrapper-0.1.jar",
          "size": 17282,
          "sha512": "0bb196c868959498ebe32dde8fc738ba07d4a6b8c808b078ea672f9ec8efcfa502132e909154b2f346f3263231eb45f494010c72d89bad7ac9fdc90418b12939",
          "sha256": "bf2002a990acbb93b6c738cfa444ff89dcde93b5ec1c3abf97391379aece1c48",
          "sha1": "1e1e8638909cf45ab07406ea0351e772ddbca891",
          "md5": "466253966419b0a314f1f96ebc2edd98"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.noeppi_noeppi.tools",
          "module": "CurseWrapperShared",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "CurseWrapper-0.1.jar",
          "url": "CurseWrapper-0.1.jar",
          "size": 17282,
          "sha512": "0bb196c868959498ebe32dde8fc738ba07d4a6b8c808b078ea672f9ec8efcfa502132e909154b2f346f3263231eb45f494010c72d89bad7ac9fdc90418b12939",
          "sha256": "bf2002a990acbb93b6c738cfa444ff89dcde93b5ec1c3abf97391379aece1c48",
          "sha1": "1e1e8638909cf45ab07406ea0351e772ddbca891",
          "md5": "466253966419b0a314f1f96ebc2edd98"
        }
      ]
    }
  ]
}
