{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.noeppi_noeppi.tools",
    "module": "SourceTransform",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "SourceTransform-1.1.3.jar",
          "url": "SourceTransform-1.1.3.jar",
          "size": 460026,
          "sha512": "7b0f999386d4f9095d05f29f15a385cbc0c48422174734426d8fa6cea323661ee7fad40ce16617e76b94bfe7eee29d0e0e34c939abe44a9377b03a79c1ab8922",
          "sha256": "dfa3c1b90c880eb2a5c3014aef5d1dd41438e78ca49bc63d70551bfb0d6e430c",
          "sha1": "dd0798c63b60145f930b37246dc61176471c82fb",
          "md5": "02e6e737549b0a2e7403136245b9e95d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.scala-lang",
          "module": "scala-library",
          "version": {
            "requires": "2.13.8"
          }
        },
        {
          "group": "org.scala-lang.modules",
          "module": "scala-parser-combinators_2.13",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.eclipse.jdt",
          "module": "org.eclipse.jdt.core",
          "version": {
            "requires": "3.29.0"
          }
        },
        {
          "group": "org.parchmentmc",
          "module": "feather",
          "version": {
            "requires": "1.0.0.3"
          }
        },
        {
          "group": "org.parchmentmc.feather",
          "module": "io-gson",
          "version": {
            "requires": "1.0.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "SourceTransform-1.1.3.jar",
          "url": "SourceTransform-1.1.3.jar",
          "size": 460026,
          "sha512": "7b0f999386d4f9095d05f29f15a385cbc0c48422174734426d8fa6cea323661ee7fad40ce16617e76b94bfe7eee29d0e0e34c939abe44a9377b03a79c1ab8922",
          "sha256": "dfa3c1b90c880eb2a5c3014aef5d1dd41438e78ca49bc63d70551bfb0d6e430c",
          "sha1": "dd0798c63b60145f930b37246dc61176471c82fb",
          "md5": "02e6e737549b0a2e7403136245b9e95d"
        }
      ]
    }
  ]
}
